name: "Register AAP Workflow"
description: "Registers a workflow with Ansible Automation Platform using a unified JSON spec"

inputs:
  aap_url:
    description: "Ansible Automation Platform base URL"
    required: true
  aap_token:
    description: "AAP API token"
    required: true
  workflow_file:
    description: "Path to the unified workflow JSON file relative to the caller repo"
    required: true

runs:
  using: "composite"
  steps:
    - name: Debug context and validate file
      shell: bash
      run: |
        echo "📂 Current working directory: $(pwd)"
        echo "📁 Listing workspace contents:"
        ls -la .
        echo "📥 Using workflow file: '${{ inputs.workflow_file }}'"

        if [[ ! -f "${{ inputs.workflow_file }}" ]]; then
          echo "❌ ERROR: Workflow file '${{ inputs.workflow_file }}' not found in workspace."
          echo "✅ Make sure you ran actions/checkout before using this action."
          exit 1
        fi

    - name: Ensure script is executable
      shell: bash
      run: chmod +x "${{ github.action_path }}/entrypoint.sh"

    - name: Run workflow registration
      shell: bash
      run: "${{ github.action_path }}/entrypoint.sh '${{ inputs.workflow_file }}'"
      env:
        AAP_HOST: ${{ inputs.aap_url }}
        AAP_TOKEN: ${{ inputs.aap_token }}
