name: Register AAP Workflow

on:
  workflow_dispatch:

jobs:
  register-workflow:
    runs-on: self-hosted
    steps:
      - name: Checkout LOB repo
        uses: actions/checkout@v4

      - name: Register AAP Workflow
        uses: torc-poc/aap-workflow-action@v1
        with:
          aap_url: https://abc.aap-torc.xyz
          aap_token: ${{ secrets.AAP_TOKEN }}
          workflow_file: compositions/asp-sql-webapp.json
